### ISSUE TITLE
Support num.tryParse()

### ISSUE THREAD

**Issue by taosimple** [ethanblake4/dart_eval#100]
```
num SUM(List list){
  num result = 0;
  for (var v in list) {
    if (v is num) {
      result += v;
    } else if (v is String) {
      final parseV = num.tryParse(v);
      if (parseV != null) {
        list.add(parseV);
        result += parseV;
      }
    }
  }
  return result;
}

main() {
     return SUM([1, 2]);
}
```
Eval code failed with exception:
```
RangeError (index): Invalid value: Valid value range is empty: 0

When the exception was thrown, this was the stack: 
#0      _Array.[] (dart:core-patch/array.dart:10:36)
#1      Variable.boxIfNeeded (package:dart_eval/src/eval/compiler/variable.dart:73:34)
#2      compileForStatement (package:dart_eval/src/eval/compiler/statement/for.dart:17:61)
#3      compileStatement (package:dart_eval/src/eval/compiler/statement/statement.dart:31:12)
#4      compileBlock (package:dart_eval/src/eval/compiler/statement/block.dart:16:20)
#5      compileFunctionDeclaration (package:dart_eval/src/eval/compiler/declaration/function.dart:72:14)
#6      compileDeclaration (package:dart_eval/src/eval/compiler/declaration/declaration.dart:20:5)
#7      Compiler.compileSources.<anonymous closure>.<anonymous closure> (package:dart_eval/src/eval/compiler/compiler.dart:389:11)
```

**Comment by taosimple** [comment]
Find issue code at `num.tryParse`

**Comment by ethanblake4** [comment]
Support for `num.tryParse()` added in v0.7.0
