### ISSUE TITLE
split error

### ISSUE THREAD

**Issue by TaurusXi** [ethanblake4/dart_eval#107]
Modify the example Test **(String split splits on given pattern).**

From

```
List<String> test() {
              const cat = "Fluffy";
              var list = cat.split("ff");            
              return list;
            }
```
To
```
List<String> test() {
              const cat = "Fluffy";
              var list = cat.split("ff");
              ///  ------  add Code Start ---------
              int length = list.length;
              print('length -> $length');
              for(var i = 0 ; i < length; i ++){
                 print('i =>$i');
              }
              ///  ------  add Code End ---------
              return list;
            }
```

And  it's crashed !

Here is the stack.
```

Testing started at 12:03 ...
length -> 2
i =>0
package:dart_eval/src/eval/runtime/runtime.dart 639:7   Runtime.execute
package:dart_eval/src/eval/runtime/runtime.dart 618:12  Runtime.executeLib
test/string_test.dart 350:23                            main.<fn>.<fn>

dart_eval runtime exception: type 'int' is not a subtype of type '$Value' in type cast
#0      Unbox.run (package:dart_eval/src/eval/runtime/ops/primitives.dart:307:48)
#1      Runtime.execute (package:dart_eval/src/eval/runtime/runtime.dart:630:12)
#2      Runtime.executeLib (package:dart_eval/src/eval/runtime/runtime.dart:618:12)

RUNTIME STATE
=============
Program offset: 98
Stack sample: [L0: $"Fluffy", L1: $"ff", L2: [L0: "Flu", L1: "y"], L3: 2, L4: $"length -> ", L5: $"2", L6: $"length -> 2", L7: $"", L8: $"length -> 2", L9: null]
Call stack: [0, -1]
TRACE:
92: InvokeDynamic (L6.+)
93: PushReturnValue ()
94: PushArg (L8)
95: InvokeExternal (Ex#12)
96: PushReturnValue ()
97: PushConstantInt (0)
98: Unbox (L3)  <<< EXCEPTION
99: NumLt (L10 < L3)
100: JumpIfFalse (@126 if L11 == false)
101: PushConstant (C4)


Process finished with exit code 1

```

**Comment by ethanblake4** [comment]
Fixed in v0.6.1
