### ISSUE TITLE
Double and int value issue

### ISSUE THREAD

**Issue by IndroidsRohan03** [ethanblake4/dart_eval#115]
Unhandled exception:
dart_eval runtime exception: type '$double' is not a subtype of type 'double' in type cast
#0      BoxDouble.run (package:dart_eval/src/eval/runtime/ops/primitives.dart:194:53)
#1      Runtime.bridgeCall (package:dart_eval/src/eval/runtime/runtime.dart:693:12)
#2      EvalStaticFunctionPtr.call (package:dart_eval/src/eval/runtime/function.dart:78:13)

dart_eval runtime exception: type '$int' is not a subtype of type 'int' in type cast
#0      BoxInt.run (package:dart_eval/src/eval/runtime/ops/primitives.dart:175:50)
#1      Runtime.bridgeCall (package:dart_eval/src/eval/runtime/runtime.dart:693:12)
#2      EvalStaticFunctionPtr.call (package:dart_eval/src/eval/runtime/function.dart:78:13)

**Comment by IndroidsRohan03** [comment]
sorry to make you all trouble. With num it works..
