### ISSUE TITLE
Cannot set a object's fields to a null value

### ISSUE THREAD

**Issue by Noobware1** [ethanblake4/dart_eval#135]
i have created a object using $Instance with non final fields but when i try to set the property to null value i am getting this error.

(the nullable value is returned by function using try catch)

```
dart_eval runtime exception: type 'Null' is not a subtype of type '$Value' in type cast
#0      SetObjectProperty.run (package:dart_eval/src/eval/runtime/ops/objects.dart:225:57)
#1      Runtime.bridgeCall (package:dart_eval/src/eval/runtime/runtime.dart:838:12)
#2      EvalStaticFunctionPtr.call (package:dart_eval/src/eval/runtime/function.dart:86:13)
```

**Comment by Noobware1** [comment]
My bad I was returning null instead of $null()
