### ISSUE TITLE
type '$int' is not a subtype of type 'int' in type cast on BoxInt.run

### ISSUE THREAD

**Issue by Noobware1** [ethanblake4/dart_eval#139]
i am trying to do
```
import 'dart:math';

main() {
return transfrom("ZAAiPZZiZAPZZAiAPZZZZZPZZiiAPZZAiZPZZiAAPZZZZAPZZZZZPZZAZPZAAiPZAAZPZZAZPZZAAAPZZAZPZZZAAPZZiZZPZZAiZPZZAiAPZZZAAPZZZZZPZZAZPZZiZZPZZAZiPZZiiiPZZZiAPZAAiPAAAiPZZZAAPZZAAiPZZZAiPZZAiZPZZZZAPZiiZZPZiZZZPAAZZPZZiZZPZZAiiPZiiZZPZZAiiPZZZZAPZZZZZPAiZiPZZiZiPZZiZZPZZiiAPZZZAAPZZAAiPZZZAiPZZAiZPZAAiPZiiZZPZiZZZPZZiiAPZZZAAPZZiAAPZZZAiPZZAiZPAiiZPZZAZPZAZAPZZAiZPZiZZZPZiiZiPZZAiiPAAAAPAZZZPZiiiiPZZiAiPZZZAiPZiZZiPZZZiZPZZAZiPAiAAPZiZiAPZiZiAPZiZiAPZAZAPZAAZPZAAZPAZAZPZZAZPZAiiZPZAAZPZAAiPZAAZP", 45, "iZAPgKQVv", 11, 3);
}


 String transfrom(String c, int d, String f, int a, int g) {
    var e = "";
    for (var h = 0, k = c.length; h < k; h++) {
      String l = "";
      while (c[h] != f[g]) {
        l += c[h];
        h++;
      }
      for (var m = 0; m < f.length; m++) {
        l = l.replaceAll(RegExp(f[m], multiLine: true), m.toString());
      }

      print(g);
    }
    return '';
  }
```

but I am keep getting this error 
```
dart_eval runtime exception: type '$int' is not a subtype of type 'int' in type cast
#0      BoxInt.run (package:dart_eval/src/eval/runtime/ops/primitives.dart:179:50)
#1      Runtime.execute (package:dart_eval/src/eval/runtime/runtime.dart:814:12)
#2      Runtime.executeLib (package:dart_eval/src/eval/runtime/runtime.dart:802:12)
at transfrom()
at main()

RUNTIME STATE
=============
Program offset: 231
Stack sample: [L0: $"ZAAiPZZiZAPZZAiAPZZZZZPZZiiAPZZAiZPZZiAAPZZZZAPZZZZZPZZAZPZAAiPZAAZPZZAZPZZAAAPZZAZPZZZAAPZZiZZPZZAiZPZZAiAPZZZAAPZZZZZPZZAZPZZiZZPZZAZiPZZiiiPZZZiAPZAAiPAAAiPZZZAAPZZAAiPZZZAiPZZAiZPZZZZAPZiiZZPZiZZZPAAZZPZZiZZPZZAiiPZiiZZPZZAiiPZZZZAPZZZZZPAiZiPZZiZiPZZiZZPZZiiAPZZZAAPZZAAiPZZZAiPZZAiZPZAAiPZiiZZPZiZZZPZZiiAPZZZAAPZZiAAPZZZAiPZZAiZPAiiZPZZAZPZAZAPZZAiZPZiZZZPZiiZiPZZAiiPAAAAPAZZZPZiiiiPZZiAiPZZZAiPZiZZiPZZZiZPZZAZiPAiAAPZiZiAPZiZiAPZiZiAPZAZAPZAAZPZAAZPAZAZPZZAZPZAiiZPZAAZPZAAiPZAAZP", L1: 45, L2: $"iZAPgKQVv", L3: 11, L4: $3, L5: "", L6: $4, L7: 490, L8: true, L9: $"1220"]
Call stack: [0, -1, 18]
TRACE:
225: Unbox (L10)
226: NumAdd (L10 + L14)
227: CopyValue (L10 <-- L15)
228: Pop (5)
229: JumpConstant (@195)
230: Pop (3)
231: BoxInt (L4)  <<< EXCEPTION
232: PushArg (L4)
233: InvokeExternal (Ex#0)
234: PushReturnValue ()

#0      Runtime.execute (package:dart_eval/src/eval/runtime/runtime.dart:824:7)
#1      Runtime.executeLib (package:dart_eval/src/eval/runtime/runtime.dart:802:12)
#2      value (package:dart_eval/lol.dart:66:23)
#3      value (package:dart_eval/lol.dart)
#4      main (package:dart_eval/lol.dart:69:9)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:294:33)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
```

as for [] operator i have properly add it.
```
   '[]': BridgeMethodDef(
            BridgeFunctionDef(
                returns: BridgeTypeAnnotation(BridgeTypeRef(CoreTypes.string)),
                params: [
                  BridgeParameter('index',
                      BridgeTypeAnnotation(BridgeTypeRef(CoreTypes.int)), false)
                ]),
            isStatic: false),
       
 static const $Function __indexGet = $Function(_indexGet);

  static $Value? _indexGet(
      Runtime runtime, $Value? target, List<$Value?> args) {
    final idx = args[0]! as $int;
    return $String((target!.$value as String)[idx.$value]);
  }
```

**Comment by ethanblake4** [comment]
Fixed in v0.7.1
