### ISSUE TITLE
Method not found [] on int at unknown

### ISSUE THREAD

**Issue by cuifengcn** [ethanblake4/dart_eval#148]
I have multi Compiler(), when running individually, everything functions properly; however, upon completing one execution and proceeding to the next, an error is encountered, as follows:
```
Method not found [] on int at unknown (file package:music/music_main.dart)

The relevant error-causing widget was: 
  NavigationView NavigationView:file:///C:/Users/14438/AndroidStudioProjects/xx/lib/screens/xx.dart:91:18
When the exception was thrown, this was the stack: 
#0      Compiler.compileSources (package:dart_eval/src/eval/compiler/compiler.dart:497:7)
#1      Compiler.compile (package:dart_eval/src/eval/compiler/compiler.dart:164:12)
```
Furthermore, I am entirely perplexed as to why such an error would be reported.

**Comment by ethanblake4** [comment]
I need more information in order to reproduce this. Can you make a small example that demonstrates this error?
